# Generated by Django 5.2.7 on 2025-11-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Medical_Archive', '0001_initial'),
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medical_Archive.specialty'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet'),
        ),
        migrations.AddField(
            model_name='patient',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet'),
        ),
    ]
