# Generated by Django 5.2.7 on 2025-11-12 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_initial'),
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Avatar/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
