# Generated by Django 5.2.7 on 2025-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_add_monthly_appointment_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='monthly_limit',
        ),
        migrations.AlterField(
            model_name='patient',
            name='monthly_appointment_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
