# Generated by Django 5.2.7 on 2025-11-12 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_doctor_avatar_alter_doctor_wallet_alter_user_rate'),
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet'),
        ),
    ]
